version: '2'
services:
    app:
        build: ./node
        links:
            - mongo
        container_name: 'app'
        working_dir: /home/app
        ports:  #HOST:CONTAINER
            - 3000:3000 #raw express
            - 4000:4000 #browser sync
            - 5858:5858 #debug port
        env_file: 
            - .env
        volumes:
            - ../app:/home/app
        command: npm start
    # db:
    #     container_name: 'db'
    #     image: mariadb
    #     env_file: 
    #         - .env
    #     volumes:       #  追加
    #         - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    mongo:
        container_name: 'mongo'
        # https://hub.docker.com/_/mongo/
        image: mongo
        env_file: 
            - .env
        


# Mac ~/src/nodeenv/docker$ docker-compose run app npm init
# docker-compose run app npm install --save-dev gulp gulp-nodemon browser-sync
# docker-compose run app npm install --save mysql sequelize
# docker-compose run app npm install --save-dev sequelize-cli


# create database app_db;
# grant all privileges on app_db.* to 'appuser'@'%' identified by 'example';
# FLUSH PRIVILEGES;

#angular2
# docker-compose run app npm install --save @angular/{core,common,compiler,platform-browser,platform-browser-dynamic} rxjs@5.0.1 zone.js@^0.7.4 core-js
# docker-compose run app npm install --save systemjs
# docker-compose run app npm install --save-dev gulp-browserify gulp-sequence vinyl-source-stream

# docker-compose run app typings install --save --global dt~core-js 
