version: '2'
services:
    app:
        build: ./node
        container_name: 'app'
        working_dir: /home/app
        ports:  #HOST:CONTAINER
            - 3000:3000 
        volumes:
            - ../app:/home/app
        command: npm start 
# Mac ~/src/nodeenv/docker$ docker-compose run app npm init
# docker-compose run app npm install --save-dev gulp gulp-nodemon browser-sync